### ISSUE TITLE
Test failures with tzdata 2020c

### ISSUE THREAD

**Issue by FRidh** [libical/libical#449] opened 2020-10-30 18:19 UTC
The following tests fail with 3.0.8 and tzdata 2020c:

```
  The following tests FAILED:
          1 - regression (SEGFAULT)
         36 - recur (SEGFAULT)
         41 - timezones (Failed)
         45 - libical-glib-array (Failed)
         47 - libical-glib-component (Failed)
         56 - libical-glib-timezone (Failed)
```

**Comment by winterz** [comment] 2020-11-07 13:40
> The following tests fail with 3.0.8 and tzdata 2020c:
> 
> ```
>   The following tests FAILED:
>           1 - regression (SEGFAULT)
>          36 - recur (SEGFAULT)
>          41 - timezones (Failed)
>          45 - libical-glib-array (Failed)
>          47 - libical-glib-component (Failed)
>          56 - libical-glib-timezone (Failed)
> ```
A similar issue (https://github.com/libical/libical/issues/454)  for the Mageia linux distro. The problem there seems to be due to TZif2 formatted files showing up in the system's zoneinfo.  Could this be the case  here as well?

**Comment by jtojnar** [comment] 2020-11-07 14:02
Apparently the timezone dumps have switched to a "slim" format since 2020b. For now, we (NixOS) have [switched](https://github.com/NixOS/nixpkgs/pull/102946) tzdata back to the old "fat" format.

**Comment by ksmurchison** [comment] 2020-11-11 13:54
Duplicate of #454

**Closed by ksmurchison** 2020-11-11 13:54 UTC

**Comment by ksmurchison** [comment] 2020-11-17 15:09
Should be fixed by https://github.com/libical/libical/commit/c7e767bfe1d218aaf845686f9811195cecc7be2a
