### ISSUE TITLE
Built errors in In Windows 64-bit machine 

### ISSUE THREAD

**Issue by chitrac** [libical/libical#237] opened 2016-06-16 09:21 UTC
**Hi ,
As requested please find the errors that I encountered when i built the source code on windows.****

Error   1   error PRJ0019: A tool returned an error code from "Performing Custom Build Step"    libical libical
Error   2   error BK1506 : cannot open file '.\Debug\icalarray.sbr': No such file or directory  BSCMAKE libical
Error   11  error C2146: syntax error : missing ')' before identifier 'ICAL_PACKAGE'    c:\libical\libical\src\libicalvcal\icalvcal.c   194 libicalvcal
Error   13  error C2059: syntax error : ')' c:\libical\libical\src\libicalvcal\icalvcal.c   195 libicalvcal
Error   34  fatal error C1083: Cannot open source file: '.\vcaltest.c': No such file or directory   c1  libicalvcal
Error   51  error C2065: 'O_RDWR' : undeclared identifier   c:\libical\libical\src\libicalss\icaldirset.c   69  libicalss
Error   52  error C2065: 'O_CREAT' : undeclared identifier  c:\libical\libical\src\libicalss\icaldirset.c   69  libicalss
Error   53  error C2099: initializer is not a constant  c:\libical\libical\src\libicalss\icaldirset.c   69  libicalss
Error   58  error C2079: 'c_file' uses undefined struct '_finddata_t'   c:\libical\libical\src\libicalss\icaldirset.c   145 libicalss
Error   61  error C2224: left of '.name' must have struct/union type    c:\libical\libical\src\libicalss\icaldirset.c   160 libicalss
Error   62  error C2224: left of '.name' must have struct/union type    c:\libical\libical\src\libicalss\icaldirset.c   160 libicalss
Error   64  error C2224: left of '.name' must have struct/union type    c:\libical\libical\src\libicalss\icaldirset.c   164 libicalss
Error   68  error C2079: 'sbuf' uses undefined struct 'stat'    c:\libical\libical\src\libicalss\icaldirset.c   179 libicalss
Error   71  error C2224: left of '.st_mode' must have struct/union type c:\libical\libical\src\libicalss\icaldirset.c   191 libicalss
Error   74  error C2065: 'O_RDONLY' : undeclared identifier c:\libical\libical\src\libicalss\icaldirset.c   218 libicalss
Error   76  error C2065: 'O_RDWR' : undeclared identifier   c:\libical\libical\src\libicalss\icaldirset.c   227 libicalss
Error   77  error C2065: 'O_CREAT' : undeclared identifier  c:\libical\libical\src\libicalss\icaldirset.c   227 libicalss
Error   79  error C2065: 'MAXPATHLEN' : undeclared identifier   c:\libical\libical\src\libicalss\icaldirset.c   268 libicalss
Error   80  error C2057: expected constant expression   c:\libical\libical\src\libicalss\icaldirset.c   268 libicalss
Error   81  error C2466: cannot allocate an array of constant size 0    c:\libical\libical\src\libicalss\icaldirset.c   268 libicalss
Error   82  error C2133: 'path' : unknown size  c:\libical\libical\src\libicalss\icaldirset.c   268 libicalss
Error   85  error C2065: 'MAXPATHLEN' : undeclared identifier   c:\libical\libical\src\libicalss\icaldirset.c   295 libicalss
Error   86  error C2057: expected constant expression   c:\libical\libical\src\libicalss\icaldirset.c   295 libicalss
Error   87  error C2466: cannot allocate an array of constant size 0    c:\libical\libical\src\libicalss\icaldirset.c   295 libicalss
Error   90  error C2065: 'MAXPATHLEN' : undeclared identifier   c:\libical\libical\src\libicalss\icaldirset.c   318 libicalss
Error   91  error C2065: 'MAXPATHLEN' : undeclared identifier   c:\libical\libical\src\libicalss\icaldirset.c   319 libicalss
Error   93  error C2065: 'MAXPATHLEN' : undeclared identifier   c:\libical\libical\src\libicalss\icaldirset.c   331 libicalss
Error   94  error C2057: expected constant expression   c:\libical\libical\src\libicalss\icaldirset.c   331 libicalss
Error   95  error C2466: cannot allocate an array of constant size 0    c:\libical\libical\src\libicalss\icaldirset.c   331 libicalss
Error   96  error C2065: 'MAXPATHLEN' : undeclared identifier   c:\libical\libical\src\libicalss\icaldirset.c   380 libicalss
Error   107 error C2065: 'MAXPATHLEN' : undeclared identifier   c:\libical\libical\src\libicalss\icaldirset.c   588 libicalss
Error   108 error C2057: expected constant expression   c:\libical\libical\src\libicalss\icaldirset.c   588 libicalss
Error   109 error C2466: cannot allocate an array of constant size 0    c:\libical\libical\src\libicalss\icaldirset.c   588 libicalss
Error   110 error C2133: 'path' : unknown size  c:\libical\libical\src\libicalss\icaldirset.c   588 libicalss
Error   111 error C2065: 'MAXPATHLEN' : undeclared identifier   c:\libical\libical\src\libicalss\icaldirset.c   604 libicalss
Error   116 error C2065: 'O_RDWR' : undeclared identifier   c:\libical\libical\src\libicalss\icalfileset.c  39  libicalss
Error   117 error C2065: 'O_CREAT' : undeclared identifier  c:\libical\libical\src\libicalss\icalfileset.c  39  libicalss
Error   118 error C2099: initializer is not a constant  c:\libical\libical\src\libicalss\icalfileset.c  39  libicalss
Error   122 error C2065: 'O_RDONLY' : undeclared identifier c:\libical\libical\src\libicalss\icalfileset.c  57  libicalss
Error   124 error C2065: 'O_RDONLY' : undeclared identifier c:\libical\libical\src\libicalss\icalfileset.c  66  libicalss
Error   132 error C2079: 'sbuf' uses undefined struct 'stat'    c:\libical\libical\src\libicalss\icalfileset.c  206 libicalss
Error   135 error C2224: left of '.st_mode' must have struct/union type c:\libical\libical\src\libicalss\icalfileset.c  223 libicalss
Error   136 error C2224: left of '.st_size' must have struct/union type c:\libical\libical\src\libicalss\icalfileset.c  229 libicalss
Error   142 error C2065: 'MAXPATHLEN' : undeclared identifier   c:\libical\libical\src\libicalss\icalfileset.c  341 libicalss
Error   143 error C2057: expected constant expression   c:\libical\libical\src\libicalss\icalfileset.c  341 libicalss
Error   144 error C2466: cannot allocate an array of constant size 0    c:\libical\libical\src\libicalss\icalfileset.c  341 libicalss
Error   145 error C2133: 'tmp' : unknown size   c:\libical\libical\src\libicalss\icalfileset.c  341 libicalss
Error   147 error C2065: 'MAXPATHLEN' : undeclared identifier   c:\libical\libical\src\libicalss\icalfileset.c  367 libicalss
Error   149 error C2065: 'IO_SSIZE_T' : undeclared identifier   c:\libical\libical\src\libicalss\icalfileset.c  393 libicalss
Error   150 error C2146: syntax error : missing ';' before identifier 'sz'  c:\libical\libical\src\libicalss\icalfileset.c  393 libicalss
Error   151 error C2065: 'sz' : undeclared identifier   c:\libical\libical\src\libicalss\icalfileset.c  393 libicalss
Error   152 error C2065: 'sz' : undeclared identifier   c:\libical\libical\src\libicalss\icalfileset.c  397 libicalss
Error   154 error C2065: 'IO_SIZE_T' : undeclared identifier    c:\libical\libical\src\libicalss\icalfileset.c  397 libicalss
Error   155 error C2146: syntax error : missing ')' before identifier 'strlen'  c:\libical\libical\src\libicalss\icalfileset.c  397 libicalss
Error   156 error C2065: 'sz' : undeclared identifier   c:\libical\libical\src\libicalss\icalfileset.c  398 libicalss
Error   157 error C2065: 'IO_SSIZE_T' : undeclared identifier   c:\libical\libical\src\libicalss\icalfileset.c  398 libicalss
Error   158 error C2146: syntax error : missing ')' before identifier 'strlen'  c:\libical\libical\src\libicalss\icalfileset.c  398 libicalss
Error   160 error C2143: syntax error : missing ';' before ')'  c:\libical\libical\src\libicalss\icalfileset.c  398 libicalss
Error   161 error C2065: 'sz' : undeclared identifier   c:\libical\libical\src\libicalss\icalfileset.c  406 libicalss
Error   162 error C2143: syntax error : missing '{' before '->' c:\libical\libical\src\libicalss\icalfileset.c  409 libicalss
Error   163 error C2059: syntax error : '->'    c:\libical\libical\src\libicalss\icalfileset.c  409 libicalss
Error   164 error C2143: syntax error : missing ')' before '->' c:\libical\libical\src\libicalss\icalfileset.c  417 libicalss
Error   165 error C2143: syntax error : missing '{' before '->' c:\libical\libical\src\libicalss\icalfileset.c  417 libicalss
Error   166 error C2059: syntax error : '->'    c:\libical\libical\src\libicalss\icalfileset.c  417 libicalss
Error   167 error C2059: syntax error : 'return'    c:\libical\libical\src\libicalss\icalfileset.c  423 libicalss
Error   168 error C2059: syntax error : '}' c:\libical\libical\src\libicalss\icalfileset.c  424 libicalss
Error   194 error C2065: 'ICAL_PACKAGE' : undeclared identifier c:\libical\libical\src\libicalss\icalmessage.c  152 libicalss
Error   195 error C2065: 'ICAL_VERSION' : undeclared identifier c:\libical\libical\src\libicalss\icalmessage.c  152 libicalss
Error   251 error C2065: 'MAXPATHLEN' : undeclared identifier   c:\libical\libical\src\libicalss\icalcalendar.c 60  libicalss
Error   252 error C2057: expected constant expression   c:\libical\libical\src\libicalss\icalcalendar.c 60  libicalss
Error   253 error C2466: cannot allocate an array of constant size 0    c:\libical\libical\src\libicalss\icalcalendar.c 60  libicalss
Error   254 error C2133: 'path' : unknown size  c:\libical\libical\src\libicalss\icalcalendar.c 60  libicalss
Error   256 error C2065: 'MAXPATHLEN' : undeclared identifier   c:\libical\libical\src\libicalss\icalcalendar.c 67  libicalss
Error   258 error C2065: 'MAXPATHLEN' : undeclared identifier   c:\libical\libical\src\libicalss\icalcalendar.c 68  libicalss
Error   260 error C2065: 'MAXPATHLEN' : undeclared identifier   c:\libical\libical\src\libicalss\icalcalendar.c 69  libicalss
Error   261 error C2065: 'MAXPATHLEN' : undeclared identifier   c:\libical\libical\src\libicalss\icalcalendar.c 70  libicalss
Error   271 error C2065: 'MAXPATHLEN' : undeclared identifier   c:\libical\libical\src\libicalss\icalcalendar.c 168 libicalss
Error   272 error C2057: expected constant expression   c:\libical\libical\src\libicalss\icalcalendar.c 168 libicalss
Error   273 error C2466: cannot allocate an array of constant size 0    c:\libical\libical\src\libicalss\icalcalendar.c 168 libicalss
Error   274 error C2133: 'dir' : unknown size   c:\libical\libical\src\libicalss\icalcalendar.c 168 libicalss
Error   275 error C2065: 'MAXPATHLEN' : undeclared identifier   c:\libical\libical\src\libicalss\icalcalendar.c 173 libicalss
Error   276 error C2065: 'MAXPATHLEN' : undeclared identifier   c:\libical\libical\src\libicalss\icalcalendar.c 174 libicalss
Error   277 error C2065: 'MAXPATHLEN' : undeclared identifier   c:\libical\libical\src\libicalss\icalcalendar.c 175 libicalss
Error   278 error C2065: 'MAXPATHLEN' : undeclared identifier   c:\libical\libical\src\libicalss\icalcalendar.c 176 libicalss
Error   280 error C2065: 'MAXPATHLEN' : undeclared identifier   c:\libical\libical\src\libicalss\icalcalendar.c 189 libicalss
Error   281 error C2057: expected constant expression   c:\libical\libical\src\libicalss\icalcalendar.c 189 libicalss
Error   282 error C2466: cannot allocate an array of constant size 0    c:\libical\libical\src\libicalss\icalcalendar.c 189 libicalss
Error   283 error C2133: 'path' : unknown size  c:\libical\libical\src\libicalss\icalcalendar.c 189 libicalss
Error   284 error C2065: 'MAXPATHLEN' : undeclared identifier   c:\libical\libical\src\libicalss\icalcalendar.c 194 libicalss
Error   285 error C2065: 'MAXPATHLEN' : undeclared identifier   c:\libical\libical\src\libicalss\icalcalendar.c 195 libicalss
Error   286 error C2065: 'MAXPATHLEN' : undeclared identifier   c:\libical\libical\src\libicalss\icalcalendar.c 196 libicalss
Error   287 error C2065: 'MAXPATHLEN' : undeclared identifier   c:\libical\libical\src\libicalss\icalcalendar.c 197 libicalss
Error   289 error C2065: 'MAXPATHLEN' : undeclared identifier   c:\libical\libical\src\libicalss\icalcalendar.c 208 libicalss
Error   290 error C2057: expected constant expression   c:\libical\libical\src\libicalss\icalcalendar.c 208 libicalss
Error   291 error C2466: cannot allocate an array of constant size 0    c:\libical\libical\src\libicalss\icalcalendar.c 208 libicalss
Error   292 error C2133: 'path' : unknown size  c:\libical\libical\src\libicalss\icalcalendar.c 208 libicalss
Error   293 error C2065: 'MAXPATHLEN' : undeclared identifier   c:\libical\libical\src\libicalss\icalcalendar.c 213 libicalss
Error   294 error C2065: 'MAXPATHLEN' : undeclared identifier   c:\libical\libical\src\libicalss\icalcalendar.c 214 libicalss
Error   295 error C2065: 'MAXPATHLEN' : undeclared identifier   c:\libical\libical\src\libicalss\icalcalendar.c 215 libicalss
Error   296 error C2065: 'MAXPATHLEN' : undeclared identifier   c:\libical\libical\src\libicalss\icalcalendar.c 216 libicalss
Error   298 error C2065: 'MAXPATHLEN' : undeclared identifier   c:\libical\libical\src\libicalss\icalcalendar.c 227 libicalss
Error   299 error C2057: expected constant expression   c:\libical\libical\src\libicalss\icalcalendar.c 227 libicalss
Error   300 error C2466: cannot allocate an array of constant size 0    c:\libical\libical\src\libicalss\icalcalendar.c 227 libicalss
Error   301 error C2133: 'path' : unknown size  c:\libical\libical\src\libicalss\icalcalendar.c 227 libicalss
Error   302 error C2065: 'MAXPATHLEN' : undeclared identifier   c:\libical\libical\src\libicalss\icalcalendar.c 232 libicalss
Error   303 error C2065: 'MAXPATHLEN' : undeclared identifier   c:\libical\libical\src\libicalss\icalcalendar.c 233 libicalss
Error   304 error C2065: 'MAXPATHLEN' : undeclared identifier   c:\libical\libical\src\libicalss\icalcalendar.c 234 libicalss
Error   305 error C2065: 'MAXPATHLEN' : undeclared identifier   c:\libical\libical\src\libicalss\icalcalendar.c 235 libicalss
Error   306 error BK1506 : cannot open file '.\Debug\vcaltest.sbr': No such file or directory   BSCMAKE libicalvcal
Error   308 fatal error C1083: Cannot open include file: 'libical/ical.h': No such file or directory    c:\libical\libical\src\test\recur.c 29  recur
Error   309 fatal error C1083: Cannot open include file: 'libical/ical.h': No such file or directory    c:\libical\libical\src\test\regression-classify.c   25  regression
Error   310 fatal error C1083: Cannot open include file: 'libical/ical.h': No such file or directory    c:\libical\libical\src\test\regression-component.c  24  regression
Error   311 error BK1506 : cannot open file '.\Debug\recur.sbr': No such file or directory  BSCMAKE recur
Error   312 fatal error C1083: Cannot open include file: 'libical/ical.h': No such file or directory    c:\libical\libical\src\test\regression-recur.c  26  regression
Error   313 fatal error C1083: Cannot open include file: 'libical/ical.h': No such file or directory    c:\libical\libical\src\test\regression-storage.c    29  regression
Error   314 fatal error C1083: Cannot open include file: 'libical/ical.h': No such file or directory    c:\libical\libical\src\test\regression-utils.c  24  regression
Error   315 fatal error C1083: Cannot open include file: 'libical/ical.h': No such file or directory    c:\libical\libical\src\test\regression.c    27  regression

**Comment by winterz** [comment] 2016-06-16 21:17
I've never seen that kind of output before.  Can you paste the exact commands you ran to build?
which cmake version you are using?

**Comment by chitrac** [comment] 2016-06-17 06:11
I am using Visual studio 2008 to build this source code

**Comment by nixomose** [comment] 2016-08-04 21:31
I'm having a similar problem or bunch of questions at least.

I'm using visual studio community with windows 10, brand new top of the line stuff.

So I wrote a little script...

call "c:\Program Files (x86)\Microsoft Visual Studio 14.0\vc\vcvarsall.bat"
rmdir /s /q libical
git clone https://github.com/libical/libical.git
cd libical
cmake -G "NMake Makefiles" -DUSE_BUILTIN_TZDATA=false -DSTATIC_ONLY=true -DUSE_32BIT_TIME_T=true -DICAL_GLIB=false

that gets me this:

CMake Error at CMakeLists.txt:340 (message):
  You are using a Microsoft Visual 32-bit compiler with 64-bit time.Run cmake
  again with the "-DUSE_32BIT_TIME_T=true" command line option.

So I do it again...

cmake -G "NMake Makefiles" -DUSE_BUILTIN_TZDATA=false -DSTATIC_ONLY=true -DUSE_32BIT_TIME_T=true -DICAL_GLIB=false

So that makes me a makefile.
I run nmake on that.

I get this:

C:\Users\smark\git\libical\config.h(276): fatal error C1189: #error:  "No size limited sprintf available"

So I change config.h
adding this:

#define HAVE_SNPRINTF 1

run nmake again

I get this a number of times (every time stat.h is included), but it's a warning so I let it go.

C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\sys/stat.h(229): warning C4028: formal parameter 1 different from declaration
C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\sys/stat.h(229): warning C4028: formal parameter 2 different from declaration

At this point it makes a few *.lib files.

it fails on process.exe...



[ 83%] Linking C executable process.exe
   Creating library process.lib and object process.exp
process.c.obj : error LNK2019: unresolved external symbol __imp__icalset_new referenced in function _main
process.c.obj : error LNK2019: unresolved external symbol __imp__icalset_new_file referenced in function _main
process.c.obj : error LNK2019: unresolved external symbol __imp__icalset_free referenced in function _main
process.c.obj : error LNK2019: unresolved external symbol __imp__icalset_add_component referenced in function _main
process.c.obj : error LNK2019: unresolved external symbol __imp__icalset_fetch_match referenced in function _main
process.c.obj : error LNK2019: unresolved external symbol __imp__icalset_get_first_component referenced in function _main
process.c.obj : error LNK2019: unresolved external symbol __imp__icalset_get_next_component referenced in function _main
process.c.obj : error LNK2019: unresolved external symbol __imp__icalclassify referenced in function _main
process.c.obj : error LNK2019: unresolved external symbol __imp__icalclassify_find_overlaps referenced in function _main
process.c.obj : error LNK2019: unresolved external symbol __imp__icalspanlist_new referenced in function _main
process.c.obj : error LNK2019: unresolved external symbol __imp__icalspanlist_next_free_time referenced in function _main
process.c.obj : error LNK2019: unresolved external symbol __imp__icalmessage_new_accept_reply referenced in function _main
process.c.obj : error LNK2019: unresolved external symbol __imp__icalmessage_new_decline_reply referenced in function _main
process.c.obj : error LNK2019: unresolved external symbol __imp__icalmessage_new_counterpropose_reply referenced in function _main
process.c.obj : error LNK2019: unresolved external symbol __imp__icalmessage_new_delegate_reply referenced in function _main
process.c.obj : error LNK2019: unresolved external symbol __imp__icalmessage_new_error_reply referenced in function _main
process.exe : fatal error LNK1120: 16 unresolved externals
LINK Pass 1 failed. with 1120
NMAKE : fatal error U1077: '"C:\Program Files\CMake\bin\cmake.exe"' : return code '0xffffffff'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.

Now I don't care much about the test stuff, but what I do need is a 64 bit library, and the library it built is 32 bit because when I try and link against my 64 bit program I get an error saying it's a 32 bit library.

How do I make it use the 64 bit compiler?
There doesn't seem to be a switch for that in CMakeLists.txt

Please forgive my ignorance, I'm a linux guy but I have to make this work on windows too.
Thanks for your help.

**Comment by winterz** [comment] 2016-08-05 15:10
hmm... I wonder if you need to use a 64-bit version of CMake to build a 64-bit executable on Windows.  Are you using a 32-bit CMake?

**Comment by nixomose** [comment] 2016-08-06 00:19
I'll give it a whirl. You're from uncensored, right?
I'm Ford ][ :-)

**Comment by winterz** [comment] 2016-08-06 13:27
also make sure you are building inside a 64-bit MSVC2015 console.
or run C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat x64 first

**Comment by nixomose** [comment] 2016-08-08 20:52
just checked, I installed only the 64 bit version of cmake

**Comment by nixomose** [comment] 2016-08-09 13:46
so I think the x64 on the end of vcvarsall.bat did the trick. I didn't know about that, thanks.
I still got the snprintf problem, but that I can work around. thanks. I'll let you know if something else goes bad.

**Comment by winterz** [comment] 2016-08-09 16:44
thanks for the feedback.  I'll add more info to the Install.txt and also investigate the snprintf thing using MSV2015.  I have never tried MSVC2015 previously.

**Comment by winterz** [comment] 2016-08-09 19:58
indeed, the build does fail with MSVC 2015 exactly as you describe.  I'll try to fix properly.

**Comment by jasongisstl** [comment] 2017-07-14 14:48
I am getting the same issue that @nixomose described (the linking errors for process.exe), whether I build for 32 or 64-bit on Windows (Visual Studio 2015).

`cmake -G "NMake Makefiles" -DSTATIC_ONLY=true -DUSE_32BIT_TIME_T=false -DICAL_GLIB=false`
Succeeds, then I receive the linking errors above when running `nmake`.

Was a solution to this added? Or is there some workaround?

Apologies for bumping a closed issue, but the above all seems relevant.

**Comment by winterz** [comment] 2017-07-18 13:25
what version are you using?  I can try to reproduce in my Windows 10 system with VS2015

**Comment by jasongisstl** [comment] 2017-07-18 15:41
Thank you very much!

This was using the latest version at the time of posting. I assume so, anyway - whatever you get using `git clone https://github.com/libical/libical.git`.

Unfortunately, I'm away from home at the moment so can't check the source for the exact version this week.

**Comment by winterz** [comment] 2017-07-19 14:10
verified. seems to be caused by building static_only.  I'll investigate.

**Comment by winterz** [comment] 2017-07-19 16:02
should be fixed in de72d59729f526cd51f78704f26f89ded253b351
please test.

**Closed by winterz** 2017-07-19 16:02 UTC

**Comment by jasongisstl** [comment] 2017-07-24 09:35
I can verify that this is fixed now.

Thank you so much for jumping on this so quickly - very much appreciated!

**Comment by winterz** [comment] 2017-07-24 12:09
I'm not happy about the fix though.  I will think about a better solution.  In the meantime, I'm glad it works for you now.
