### ISSUE TITLE
build generator Ninja with static libs fails on Mac

### ISSUE THREAD

**Issue by thierryba** [libical/libical#475] opened 2021-01-25 17:33 UTC
Hello, I tried libical (both 3.0.8 and then 3.0.9)
if I configure with cmake -GNinja -DSTATIC_ONLY=true -DICAL_GLIB=false ../libical-3.0.8 

I'm getting this

CMake Error:
...
  failed with:

   ninja: error: build.ninja:624: multiple rules generate lib/libical_cxx.a [-w dupbuild=err]

It works fine with Unix Makefiles.

**Comment by winterz** [comment] 2021-01-25 17:57
verified. happens in 3.0.9 and master as well.

**Comment by winterz** [comment] 2021-01-25 18:06
`cmake -GNinja -DICAL_GLIB=false` works
`cmake -GNinja -DSHARED_ONLY=true -DICAL_GLIB=false` works
`cmake -GNinja -DSTATIC_ONLY=true -DICAL_GLIB=false` fails

**Comment by krop** [comment] 2021-01-27 14:45
the issue comes from src/libical/CMakeLists.txt.

libical always builds ical_cxx (line 327) but if SHARED_ONLY is false, it also builds ical_cxx-static and tries to rename the produced library to ical_cxx on !MSVC (https://github.com/libical/libical/blob/master/src/libical/CMakeLists.txt#L342)

**Comment by kuruczgy** [comment] 2021-01-31 00:38
I think #477 fixes exactly this, please take a look if you can.

**Comment by thierryba** [comment] 2021-02-02 16:56
@kuruczgy 
Sorry but that did not work
the output of CMake is

`thierry@tb libical % cmake -GNinja -DSTATIC_ONLY=true -DICAL_GLIB=false
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.


-- The C compiler identification is AppleClang 12.0.0.12000032
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/local/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- The CXX compiler identification is AppleClang 12.0.0.12000032
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/local/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Perl: /usr/local/bin/perl (found version "5.32.1") 
-- The following ICU libraries were not found:
--   uc (required)
--   i18n (required)
-- Failed to find all ICU components (missing: ICU_INCLUDE_DIR ICU_LIBRARY _ICU_REQUIRED_LIBS_FOUND) 
-- Optional package Berkeley DB was not found
-- Looking for include file byteswap.h
-- Looking for include file byteswap.h - not found
-- Looking for include file dirent.h
-- Looking for include file dirent.h - found
-- Looking for include file endian.h
-- Looking for include file endian.h - not found
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - found
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for include file sys/endian.h
-- Looking for include file sys/endian.h - not found
-- Looking for include file sys/param.h
-- Looking for include file sys/param.h - found
-- Looking for include file sys/utsname.h
-- Looking for include file sys/utsname.h - found
-- Looking for include file fcntl.h
-- Looking for include file fcntl.h - found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Looking for include file wctype.h
-- Looking for include file wctype.h - found
-- Looking for include file stdbool.h
-- Looking for include file stdbool.h - found
-- Looking for access
-- Looking for access - found
-- Looking for fork
-- Looking for fork - found
-- Looking for getopt
-- Looking for getopt - found
-- Looking for getpid
-- Looking for getpid - found
-- Looking for getpwent
-- Looking for getpwent - found
-- Looking for gmtime_r
-- Looking for gmtime_r - found
-- Looking for localtime_r
-- Looking for localtime_r - found
-- Looking for mkdir
-- Looking for mkdir - found
-- Looking for open
-- Looking for open - found
-- Looking for nanosleep
-- Looking for nanosleep - found
-- Looking for signal
-- Looking for signal - found
-- Looking for stat
-- Looking for stat - found
-- Looking for strdup
-- Looking for strdup - found
-- Looking for strcasecmp
-- Looking for strcasecmp - found
-- Looking for strncasecmp
-- Looking for strncasecmp - found
-- Looking for read
-- Looking for read - found
-- Looking for unlink
-- Looking for unlink - found
-- Looking for usleep
-- Looking for usleep - found
-- Looking for waitpid
-- Looking for waitpid - found
-- Looking for write
-- Looking for write - found
-- Looking for alarm
-- Looking for alarm - found
-- Looking for backtrace
-- Looking for backtrace - found
-- Looking for iswspace
-- Looking for iswspace - found
-- Looking for setenv
-- Looking for setenv - found
-- Looking for unsetenv
-- Looking for unsetenv - found
-- Looking for snprintf
-- Looking for snprintf - found
-- Looking for GetNumberFormat
-- Looking for GetNumberFormat - not found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of intptr_t
-- Check size of intptr_t - done
-- Check size of pid_t
-- Check size of pid_t - done
-- Check size of size_t
-- Check size of size_t - done
-- Check size of ssize_t
-- Check size of ssize_t - done
-- Check size of time_t
-- Check size of time_t - done
-- Check size of wint_t
-- Check size of wint_t - failed
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Looking for pthread_attr_get_np in pthread
-- Looking for pthread_attr_get_np in pthread - not found
-- Looking for pthread_getattr_np in pthread
-- Looking for pthread_getattr_np in pthread - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Looking for include files pthread.h, pthread_np.h
-- Looking for include files pthread.h, pthread_np.h - not found
-- Performing Test C_SUPPORTS_UNUSED_BUT_SET
-- Performing Test C_SUPPORTS_UNUSED_BUT_SET - Failed
-- Performing Test C_SUPPORTS_LOGICAL_OP
-- Performing Test C_SUPPORTS_LOGICAL_OP - Failed
-- Performing Test C_SUPPORTS_POINTER_MEMACCESS
-- Performing Test C_SUPPORTS_POINTER_MEMACCESS - Success
-- Performing Test C_SUPPORTS_FORMAT_SECURITY
-- Performing Test C_SUPPORTS_FORMAT_SECURITY - Success
-- Performing Test C_SUPPORTS_REDUNDANT_DECLS
-- Performing Test C_SUPPORTS_REDUNDANT_DECLS - Success
-- Performing Test CXX_SUPPORTS_UNUSED_BUT_SET
-- Performing Test CXX_SUPPORTS_UNUSED_BUT_SET - Failed
-- Performing Test CXX_SUPPORTS_LOGICAL_OP
-- Performing Test CXX_SUPPORTS_LOGICAL_OP - Failed
-- Performing Test CXX_SUPPORTS_POINTER_MEMACCESS
-- Performing Test CXX_SUPPORTS_POINTER_MEMACCESS - Success
-- Performing Test CXX_SUPPORTS_REORDER
-- Performing Test CXX_SUPPORTS_REORDER - Success
-- Performing Test CXX_SUPPORTS_FORMAT_SECURITY
-- Performing Test CXX_SUPPORTS_FORMAT_SECURITY - Success
-- Performing Test CXX_SUPPORTS_REDUNDANT_DECLS
-- Performing Test CXX_SUPPORTS_REDUNDANT_DECLS - Success
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- The following features have been enabled:

 * Option WITH_CXX_BINDINGS, build the C++ bindings. Requires a C++ compiler
 * Option STATIC_ONLY, Build static libraries only.
 * Option USE_BUILTIN_TZDATA, (Careful) Build using libical's built-in timezone data, else use the system timezone data on non-Windows systems. ALWAYS true on Windows. Non-Windows users should know what they're doing if they choose not to use system provided timezone data. The libical project does not guarantee that the built-in timezone data is up-to-date.
 * Option LIBICAL_BUILD_TESTING, Build tests.
 * Option ICAL_BUILD_DOCS, Build documentation

-- The following OPTIONAL packages have been found:

 * PkgConfig

-- The following REQUIRED packages have been found:

 * Perl
   Required by the libical build system.

-- The following features have been disabled:

 * Option SHARED_ONLY, Build shared (dynamic) libraries only. Takes precedence over STATIC_ONLY.
 * RSCALE support (RFC7529), build in RSCALE support
 * Berkeley DB storage support, build in support for Berkeley DB storage
 * Option ICAL_ERRORS_ARE_FATAL, icalerror_* calls will abort instead of internally signaling an error.
 * Option ICAL_ALLOW_EMPTY_PROPERTIES, Prevents empty properties from being replaced with X-LIC-ERROR properties.
 * Option GOBJECT_INTROSPECTION, Build GObject introspection "typelib" files. Requires GObject Introspection development package 0.6.7 or higher.
 * Option ICAL_GLIB_VAPI, Build Vala "vapi" files.
 * Option ICAL_GLIB, Build libical-glib interface. Requires glib 2.44 and libxml 2.7.3 development packages or higher.
 * Option ABI_DUMPER, (Developer-only) Build for abi-dumper.
 * Option ADDRESS_SANITIZER, (Developer-only) Build with the address sanitizer.
 * Option THREAD_SANITIZER, (Developer-only) Build with the thread sanitizer.
 * Option ENABLE_LTO_BUILD, Build a link-time optimized version.

-- The following OPTIONAL packages have not been found:

 * BDB, Berkeley DB storage, <https://www.oracle.com/database/berkeley-db>
   For Berkeley DB storage support
 * Doxygen, API Documentation system, <http://www.doxygen.org>
   Needed to build the API documention.

-- The following RECOMMENDED packages have not been found:

 * ICU
   For RSCALE (RFC7529) support

-- Configuring done
CMake Error at src/test/CMakeLists.txt:52 (add_dependencies):
  The dependency target "ical-static" of target "testvcal" does not exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:74 (buildme)
  src/test/CMakeLists.txt:153 (testme)


CMake Error at src/test/CMakeLists.txt:52 (add_dependencies):
  The dependency target "icalss-static" of target "testvcal" does not exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:74 (buildme)
  src/test/CMakeLists.txt:153 (testme)


CMake Error at src/test/CMakeLists.txt:59 (add_dependencies):
  The dependency target "icalss_cxx-static" of target "testvcal" does not
  exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:74 (buildme)
  src/test/CMakeLists.txt:153 (testme)


CMake Error at src/test/CMakeLists.txt:52 (add_dependencies):
  The dependency target "icalvcal-static" of target "testvcal" does not
  exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:74 (buildme)
  src/test/CMakeLists.txt:153 (testme)


CMake Error at src/test/CMakeLists.txt:52 (add_dependencies):
  The dependency target "ical-static" of target "regression" does not exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:74 (buildme)
  src/test/CMakeLists.txt:103 (testme)


CMake Error at src/test/CMakeLists.txt:52 (add_dependencies):
  The dependency target "icalss-static" of target "regression" does not
  exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:74 (buildme)
  src/test/CMakeLists.txt:103 (testme)


CMake Error at src/test/CMakeLists.txt:59 (add_dependencies):
  The dependency target "icalss_cxx-static" of target "regression" does not
  exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:74 (buildme)
  src/test/CMakeLists.txt:103 (testme)


CMake Error at src/test/CMakeLists.txt:52 (add_dependencies):
  The dependency target "icalvcal-static" of target "regression" does not
  exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:74 (buildme)
  src/test/CMakeLists.txt:103 (testme)


CMake Error at src/test/CMakeLists.txt:52 (add_dependencies):
  The dependency target "ical-static" of target "testmime" does not exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:74 (buildme)
  src/test/CMakeLists.txt:147 (testme)


CMake Error at src/test/CMakeLists.txt:52 (add_dependencies):
  The dependency target "icalss-static" of target "testmime" does not exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:74 (buildme)
  src/test/CMakeLists.txt:147 (testme)


CMake Error at src/test/CMakeLists.txt:59 (add_dependencies):
  The dependency target "icalss_cxx-static" of target "testmime" does not
  exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:74 (buildme)
  src/test/CMakeLists.txt:147 (testme)


CMake Error at src/test/CMakeLists.txt:52 (add_dependencies):
  The dependency target "icalvcal-static" of target "testmime" does not
  exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:74 (buildme)
  src/test/CMakeLists.txt:147 (testme)


CMake Error at src/test/CMakeLists.txt:52 (add_dependencies):
  The dependency target "ical-static" of target "icaltm_test" does not exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:74 (buildme)
  src/test/CMakeLists.txt:140 (testme)


CMake Error at src/test/CMakeLists.txt:52 (add_dependencies):
  The dependency target "icalss-static" of target "icaltm_test" does not
  exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:74 (buildme)
  src/test/CMakeLists.txt:140 (testme)


CMake Error at src/test/CMakeLists.txt:59 (add_dependencies):
  The dependency target "icalss_cxx-static" of target "icaltm_test" does not
  exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:74 (buildme)
  src/test/CMakeLists.txt:140 (testme)


CMake Error at src/test/CMakeLists.txt:52 (add_dependencies):
  The dependency target "icalvcal-static" of target "icaltm_test" does not
  exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:74 (buildme)
  src/test/CMakeLists.txt:140 (testme)


CMake Error at src/test/CMakeLists.txt:52 (add_dependencies):
  The dependency target "ical-static" of target "stow" does not exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:122 (buildme)


CMake Error at src/test/CMakeLists.txt:52 (add_dependencies):
  The dependency target "icalss-static" of target "stow" does not exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:122 (buildme)


CMake Error at src/test/CMakeLists.txt:59 (add_dependencies):
  The dependency target "icalss_cxx-static" of target "stow" does not exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:122 (buildme)


CMake Error at src/test/CMakeLists.txt:52 (add_dependencies):
  The dependency target "icalvcal-static" of target "stow" does not exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:122 (buildme)


CMake Error at src/test/CMakeLists.txt:52 (add_dependencies):
  The dependency target "ical-static" of target "parser" does not exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:108 (buildme)


CMake Error at src/test/CMakeLists.txt:52 (add_dependencies):
  The dependency target "icalss-static" of target "parser" does not exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:108 (buildme)


CMake Error at src/test/CMakeLists.txt:59 (add_dependencies):
  The dependency target "icalss_cxx-static" of target "parser" does not
  exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:108 (buildme)


CMake Error at src/test/CMakeLists.txt:52 (add_dependencies):
  The dependency target "icalvcal-static" of target "parser" does not exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:108 (buildme)


CMake Error at src/test/CMakeLists.txt:52 (add_dependencies):
  The dependency target "ical-static" of target "process" does not exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:74 (buildme)
  src/test/CMakeLists.txt:158 (testme)


CMake Error at src/test/CMakeLists.txt:52 (add_dependencies):
  The dependency target "icalss-static" of target "process" does not exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:74 (buildme)
  src/test/CMakeLists.txt:158 (testme)


CMake Error at src/test/CMakeLists.txt:59 (add_dependencies):
  The dependency target "icalss_cxx-static" of target "process" does not
  exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:74 (buildme)
  src/test/CMakeLists.txt:158 (testme)


CMake Error at src/test/CMakeLists.txt:52 (add_dependencies):
  The dependency target "icalvcal-static" of target "process" does not exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:74 (buildme)
  src/test/CMakeLists.txt:158 (testme)


CMake Error at src/test/CMakeLists.txt:52 (add_dependencies):
  The dependency target "ical-static" of target "icalrecur_test" does not
  exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:134 (buildme)


CMake Error at src/test/CMakeLists.txt:52 (add_dependencies):
  The dependency target "icalss-static" of target "icalrecur_test" does not
  exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:134 (buildme)


CMake Error at src/test/CMakeLists.txt:59 (add_dependencies):
  The dependency target "icalss_cxx-static" of target "icalrecur_test" does
  not exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:134 (buildme)


CMake Error at src/test/CMakeLists.txt:52 (add_dependencies):
  The dependency target "icalvcal-static" of target "icalrecur_test" does not
  exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:134 (buildme)


CMake Error at src/test/CMakeLists.txt:52 (add_dependencies):
  The dependency target "ical-static" of target "recur" does not exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:74 (buildme)
  src/test/CMakeLists.txt:128 (testme)


CMake Error at src/test/CMakeLists.txt:52 (add_dependencies):
  The dependency target "icalss-static" of target "recur" does not exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:74 (buildme)
  src/test/CMakeLists.txt:128 (testme)


CMake Error at src/test/CMakeLists.txt:59 (add_dependencies):
  The dependency target "icalss_cxx-static" of target "recur" does not exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:74 (buildme)
  src/test/CMakeLists.txt:128 (testme)


CMake Error at src/test/CMakeLists.txt:52 (add_dependencies):
  The dependency target "icalvcal-static" of target "recur" does not exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:74 (buildme)
  src/test/CMakeLists.txt:128 (testme)


CMake Error at src/test/CMakeLists.txt:52 (add_dependencies):
  The dependency target "ical-static" of target "builtin_timezones" does not
  exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:74 (buildme)
  src/test/CMakeLists.txt:170 (testme)


CMake Error at src/test/CMakeLists.txt:52 (add_dependencies):
  The dependency target "icalss-static" of target "builtin_timezones" does
  not exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:74 (buildme)
  src/test/CMakeLists.txt:170 (testme)


CMake Error at src/test/CMakeLists.txt:59 (add_dependencies):
  The dependency target "icalss_cxx-static" of target "builtin_timezones"
  does not exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:74 (buildme)
  src/test/CMakeLists.txt:170 (testme)


CMake Error at src/test/CMakeLists.txt:52 (add_dependencies):
  The dependency target "icalvcal-static" of target "builtin_timezones" does
  not exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:74 (buildme)
  src/test/CMakeLists.txt:170 (testme)


CMake Error at src/test/CMakeLists.txt:52 (add_dependencies):
  The dependency target "ical-static" of target "copycluster" does not exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:87 (buildme)


CMake Error at src/test/CMakeLists.txt:52 (add_dependencies):
  The dependency target "icalss-static" of target "copycluster" does not
  exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:87 (buildme)


CMake Error at src/test/CMakeLists.txt:59 (add_dependencies):
  The dependency target "icalss_cxx-static" of target "copycluster" does not
  exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:87 (buildme)


CMake Error at src/test/CMakeLists.txt:52 (add_dependencies):
  The dependency target "icalvcal-static" of target "copycluster" does not
  exist.
Call Stack (most recent call first):
  src/test/CMakeLists.txt:87 (buildme)


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.`

**Comment by kuruczgy** [comment] 2021-02-02 17:33
Yep, I was building with `-DLIBICAL_BUILD_TESTING=false`, and did not notice that the tests depended on the -static libs.

I pushed a new version, and now the command line you gave works for me. (I added ALIAS targets for the -static libs)

**Comment by thierryba** [comment] 2021-02-04 12:47
@kuruczgy yes that seems to do the trick. Thanks!

**Comment by winterz** [comment] 2021-02-06 13:49
@kuruczgy thanks for the patch
should be fixed in 6cd49f3ff7f0238f33796c9a9d4f2166d8cbe18d

**Comment by winterz** [comment] 2021-11-21 14:13
@kuruczgy we could use your help with Ninja again.  I'm not sure if your patch has been lost/broken since February but can you take a look at #527  (might be a dupe of this issue)

**Closed** 2022-03-05 14:45 UTC
