### ISSUE TITLE
libical-glib shall use G_ADD_PRIVATE instead of deprecated g_type_class_add_private

### ISSUE THREAD

**Issue by dilyanpalauzov** [libical/libical#614] opened 2022-10-15 06:43 UTC
In the 3.0 branch (v3.0.15-13-g464c22c2) compiling libical-glib prints:
```
[98/103] Building C object src/libical-glib/CMakeFiles/ical-glib.dir/i-cal-object.c.o
/git/libical/build/src/libical-glib/i-cal-object.c: In function ‘i_cal_object_class_init’:
/git/libical/build/src/libical-glib/i-cal-object.c:227:5: warning: ‘g_type_class_add_private’ is deprecated [-Wdeprecated-declarations]
  227 |     g_type_class_add_private(class, sizeof(ICalObjectPrivate));
      |     ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/gobject/gobject.h:24,
                 from /usr/include/glib-2.0/gobject/gbinding.h:29,
                 from /usr/include/glib-2.0/glib-object.h:22,
                 from /git/libical/build/src/libical-glib/i-cal-object.h:26,
                 from /git/libical/build/src/libical-glib/i-cal-object.c:21:
/usr/include/glib-2.0/gobject/gtype.h:1346:10: note: declared here
 1346 | void     g_type_class_add_private       (gpointer                    g_class,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
/git/libical/build/src/libical-glib/i-cal-object.c: In function ‘i_cal_object_init’:
/git/libical/build/src/libical-glib/i-cal-object.c:322:13: warning: Deprecated pre-processor symbol: replace with "G_ADD_PRIVATE"
  322 |     iobject->priv = G_TYPE_INSTANCE_GET_PRIVATE(iobject, I_CAL_TYPE_OBJECT, ICalObjectPrivate);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by tintou** [comment] 2022-10-15 13:55
Duplicate of https://github.com/libical/libical/issues/600

**Closed by tintou** 2022-10-15 13:55 UTC
