### ISSUE TITLE
libical not correctly reading data from tzdb-2020d

### ISSUE THREAD

**Issue by aguador** [libical/libical#454] opened 2020-11-06 14:32 UTC
It appears that libical is not reading timezone data correctly there are multiple TZif2 file format headers, at least one of which is empty and crashes. This has been observed with libical's make test internal tests. For more details see https://gitlab.gnome.org/GNOME/evolution-data-server/-/issues/267#note_952898

**Comment by dilyanpalauzov** [comment] 2020-11-06 21:27
Please provide a timezone file in iCalendar format that causes the problem.

**Comment by aguador** [comment] 2020-11-06 21:50
I hate to admit it, but I am not sure how to do that. Is there a converter than can grab to tzdb data and convert it? The Madrid tz is causing the failure on my machine.

**Comment by dilyanpalauzov** [comment] 2020-11-06 21:54
The IANA tzdb is converted to icalendar file by a vzic tool.  llibical consumes iCalendar file.  The consumed file must be on your computer.

**Comment by aguador** [comment] 2020-11-06 22:35
Here is the file located in /usr/share/timeinfo/Europe that I presume libical uses.

[Madrid.gz](https://github.com/libical/libical/files/5503796/Madrid.gz)

**Comment by dilyanpalauzov** [comment] 2020-11-07 13:15
The provided file is in TZif2 format.  My understanding is, that the input/output of libical can be only in iCalendar format.  The source code of libical does not mention anywhere tzif/TZif, so this file is not consumed by libical and problem is not caused by libical.

**Comment by winterz** [comment] 2020-11-07 13:43
for the record, I'm updating libical's builtin zoneinfo data with tzdata2020d today and don't see any crashes in the libical testsuite.  In fact, the tzdata2020d data is has very few changes from the current builtin zoneinfo.

I agree with @dilyanpalauzov . this must be due to the system install TZif2 files .  apparently we should skip those somehow in libical.  anyone feel like making a  patch for that?

**Comment by dilyanpalauzov** [comment] 2020-11-07 13:53
Olson 2020b, 2020c and 2020d were released almost simultaneously.  The upstream bug https://gitlab.gnome.org/GNOME/evolution-data-server/-/issues/267 says that the problem comes from dropped pacificnew and the [Announcement for Olson 2020c](http://mm.icann.org/pipermail/tz-announce/2020-October/000060.html) says “tarballs now contain an empty file pacificnew”.

While the PR mentions explicitly 2020d, it might mean changes introduced by 2020c.

**Comment by aguador** [comment] 2020-11-07 14:48
> While the PR mentions explicitly 2020d, it might mean changes introduced by 2020c.

I am out of my depth here. However, after the upstream bug was closed I reviewed the history of changes in tzdb. An empty "pacficnew" was added back in 2020c to avoid problems with legacy programs. The only significant changes to code and build were in 2020b, which may be the source as Mageia skipped from 2020a to 2020d. My summary of changes attached.

[tzdb_change_summary.txt](https://github.com/libical/libical/files/5504913/tzdb_change_summary.txt)

**Comment by pterjan** [comment] 2020-11-10 14:25
From  my reading of the code icaltzutil_fetch_timezone is the one trying to read the system timezone file and which should be made either to  either skip or handle those files.

That function skips the first 20 bytes of the header and by reading https://man7.org/linux/man-pages/man5/tzfile.5.html that would be the first change as the 5th byte containing a 2 would indicate such file.

However from reading that documentation, a reader only handling v1 should be fine as the rest is added after the v1 header+data and v2 compatible readers would just skip all of those, so there is probably a bug that can be fixed instead.

The doc says v2 writers should write v1 data but it does not seem mandatory, can those files have empty v1 data? If that's the case that would be a better check as it would allow to still handle v2 files with proper v1 data.

**Comment by ksmurchison** [comment] 2020-11-10 14:38
As a co-author of RFC 8536 I suppose that I should look into this issue.

**Comment by mgorse** [comment] 2020-11-10 18:29
OpenSUSE is currently passing -b fat when compiling timezones. If we don't do this, then evolution crashes when creating a recurring appointment; initialize_rscale calls icaltimezone_get_tzid, which returns NULL. I presume we are hitting this issue. I believe -b fat was the default until recently.

**Comment by ksmurchison** [comment] 2020-11-10 19:24
That is correct.  zic -b slim now produces v2 TZif files with essentially empty v1 data (no transitions).  icaltzutil_fetch_timezone() doesn't crash on these files, but it only reads the v1 data and returns a NULL component when it doesn't see any transitions.
I'm re-writing this function to always use the v2/v3 data (if present and time_t is 8 bytes), otherwise it will use the v1 data.
I will also make sure that any libical code that calls icaltzutil_fetch_timezone() will gracefully handle a NULL component.

**Comment by FRidh** [comment] 2020-11-11 13:57
Note also https://github.com/libical/libical/issues/449 with indeed the observation the format has changed.

**Comment by ksmurchison** [comment] 2020-11-17 15:10
Should be fixed by https://github.com/libical/libical/commit/c7e767bfe1d218aaf845686f9811195cecc7be2a

**Closed by ksmurchison** 2020-11-17 15:10 UTC
