### ISSUE TITLE
Build system uses global CMAKE variables

### ISSUE THREAD

**Issue by paweljonskim** [libical/libical#502] opened 2021-07-30 08:56 UTC
Hello!
Many CMakeLists.txt use global CMAKE variables (`CMAKE_SOURCE_DIR` and `CMAKE_BUILD_DIR`) which makes impossible to add this project as subrepo in other buildsystems. Changing usage of global variables to project variables will solve the issue and should not create any additional problems.
`CMAKE_SOURCE_DIR` -> `PROJECT_SOURCE_DIR`
`CMAKE_BINARY_DIR` -> `PROJECT_BINARY_DIR`

**Comment by winterz** [comment] 2022-03-05 15:07
oops, I just created a dupe of this in #556 
I'll close that one.

**Closed** 2024-02-23 16:25 UTC
Labels: buildsystem
