### ISSUE TITLE
libical-glib-private.h:257:2: error: #endif without #if

### ISSUE THREAD

**Issue by dilyanpalauzov** [libical/libical#316] opened 2017-10-06 19:37 UTC
Compiling libical  v2.0.0-360-ga2bc4844 with cmake 3.9.3 I get
```
[ 55%] Building C object src/libical-glib/CMakeFiles/ical-glib.dir/i-cal-array.c.o
cd /git/libical/src/libical-glib && /usr/local/bin/cc -DG_LOG_DOMAIN=\"libical-glib\" -DHAVE_CONFIG_H -DLIBICAL_GLIB_COMPILATION -DWITH_CXX_BINDINGS -Dical_glib_EXPORTS -Dlibical_ical_EXPORTS -I/git/libical -I/git/libical/src -I/git/libical/src/libical  -O0 -fvisibility=hidden -Wno-deprecated -Wall -Wno-unknown-pragmas -Wextra -Winit-self -Wmissing-include-dirs -Wunused -Wno-div-by-zero -Wundef -Wpointer-arith -Wtype-limits -Wwrite-strings -Werror=return-type -Wunused-but-set-variable -Wlogical-op -Wsizeof-pointer-memaccess -Wformat -Wformat-security -Wredundant-decls -D_XOPEN_SOURCE=500 -D_DEFAULT_SOURCE -D_GNU_SOURCE -g -fPIC   -I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include -I/usr/local/include -o CMakeFiles/ical-glib.dir/i-cal-array.c.o   -c /git/libical/src/libical-glib/i-cal-array.c
In file included from /git/libical/src/libical-glib/i-cal-array.c:24:0:
/git/libical/src/libical-glib/libical-glib-private.h:20:17: warning: redundant redeclaration of ‘i_cal_component_new_full’ [-Wredundant-decls]
 ICalComponent * i_cal_component_new_full (icalcomponent *native,
                 ^~~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:15:17: note: previous declaration of ‘i_cal_component_new_full’ was here
 ICalComponent * i_cal_component_new_full (icalcomponent *native,
                 ^~~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:36:3: warning: redundant redeclaration of ‘i_cal_datetimeperiod_type_new_full’ [-Wredundant-decls]
   i_cal_datetimeperiod_type_new_full
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:26:3: note: previous declaration of ‘i_cal_datetimeperiod_type_new_full’ was here
   i_cal_datetimeperiod_type_new_full
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:40:3: warning: redundant redeclaration of ‘i_cal_datetimeperiod_type_new_default’ [-Wredundant-decls]
   i_cal_datetimeperiod_type_new_default
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:30:3: note: previous declaration of ‘i_cal_datetimeperiod_type_new_default’ was here
   i_cal_datetimeperiod_type_new_default
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:55:3: warning: redundant redeclaration of ‘i_cal_timezone_phase_new_full’ [-Wredundant-decls]
   i_cal_timezone_phase_new_full (struct icaltimezonephase native);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:46:3: note: previous declaration of ‘i_cal_timezone_phase_new_full’ was here
   i_cal_timezone_phase_new_full (struct icaltimezonephase native);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:58:3: warning: redundant redeclaration of ‘i_cal_timezone_phase_new_default’ [-Wredundant-decls]
   i_cal_timezone_phase_new_default
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:49:3: note: previous declaration of ‘i_cal_timezone_phase_new_default’ was here
   i_cal_timezone_phase_new_default
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:72:3: warning: redundant redeclaration of ‘i_cal_recurrence_type_new_full’ [-Wredundant-decls]
   i_cal_recurrence_type_new_full (struct icalrecurrencetype native);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:64:3: note: previous declaration of ‘i_cal_recurrence_type_new_full’ was here
   i_cal_recurrence_type_new_full (struct icalrecurrencetype native);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:75:3: warning: redundant redeclaration of ‘i_cal_recurrence_type_new’ [-Wredundant-decls]
   i_cal_recurrence_type_new (void);
   ^~~~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:67:3: note: previous declaration of ‘i_cal_recurrence_type_new’ was here
   i_cal_recurrence_type_new (void);
   ^~~~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:83:16: warning: redundant redeclaration of ‘i_cal_time_span_new_full’ [-Wredundant-decls]
 ICalTimeSpan * i_cal_time_span_new_full (struct icaltime_span native);
                ^~~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:79:16: note: previous declaration of ‘i_cal_time_span_new_full’ was here
 ICalTimeSpan * i_cal_time_span_new_full (struct icaltime_span native);
                ^~~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:92:17: warning: redundant redeclaration of ‘i_cal_parameter_new_full’ [-Wredundant-decls]
 ICalParameter * i_cal_parameter_new_full (icalparameter *native,
                 ^~~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:87:17: note: previous declaration of ‘i_cal_parameter_new_full’ was here
 ICalParameter * i_cal_parameter_new_full (icalparameter *native,
                 ^~~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:103:3: warning: redundant redeclaration of ‘i_cal_duration_type_new_full’ [-Wredundant-decls]
   i_cal_duration_type_new_full (struct icaldurationtype native);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:98:3: note: previous declaration of ‘i_cal_duration_type_new_full’ was here
   i_cal_duration_type_new_full (struct icaldurationtype native);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:112:16: warning: redundant redeclaration of ‘i_cal_property_new_full’ [-Wredundant-decls]
 ICalProperty * i_cal_property_new_full  (icalproperty *native,
                ^~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:107:16: note: previous declaration of ‘i_cal_property_new_full’ was here
 ICalProperty * i_cal_property_new_full  (icalproperty *native,
                ^~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:126:3: warning: redundant redeclaration of ‘i_cal_reqstat_type_new_full’ [-Wredundant-decls]
   i_cal_reqstat_type_new_full (struct icalreqstattype native);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:118:3: note: previous declaration of ‘i_cal_reqstat_type_new_full’ was here
   i_cal_reqstat_type_new_full (struct icalreqstattype native);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:129:3: warning: redundant redeclaration of ‘i_cal_reqstat_type_new_default’ [-Wredundant-decls]
   i_cal_reqstat_type_new_default (void);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:121:3: note: previous declaration of ‘i_cal_reqstat_type_new_default’ was here
   i_cal_reqstat_type_new_default (void);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:140:16: warning: redundant redeclaration of ‘i_cal_timetype_new_full’ [-Wredundant-decls]
 ICalTimetype * i_cal_timetype_new_full  (struct icaltimetype native);
                ^~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:133:16: note: previous declaration of ‘i_cal_timetype_new_full’ was here
 ICalTimetype * i_cal_timetype_new_full  (struct icaltimetype native);
                ^~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:143:3: warning: redundant redeclaration of ‘i_cal_timetype_new_default’ [-Wredundant-decls]
   i_cal_timetype_new_default (void);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:136:3: note: previous declaration of ‘i_cal_timetype_new_default’ was here
   i_cal_timetype_new_default (void);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:152:13: warning: redundant redeclaration of ‘i_cal_value_new_full’ [-Wredundant-decls]
 ICalValue * i_cal_value_new_full  (icalvalue *native,
             ^~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:147:13: note: previous declaration of ‘i_cal_value_new_full’ was here
 ICalValue * i_cal_value_new_full  (icalvalue *native,
             ^~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:166:3: warning: redundant redeclaration of ‘i_cal_timezonetype_new_full’ [-Wredundant-decls]
   i_cal_timezonetype_new_full (struct icaltimezonetype native);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:158:3: note: previous declaration of ‘i_cal_timezonetype_new_full’ was here
   i_cal_timezonetype_new_full (struct icaltimezonetype native);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:169:3: warning: redundant redeclaration of ‘i_cal_timezonetype_new_default’ [-Wredundant-decls]
   i_cal_timezonetype_new_default (void);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:161:3: note: previous declaration of ‘i_cal_timezonetype_new_default’ was here
   i_cal_timezonetype_new_default (void);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:179:3: warning: redundant redeclaration of ‘i_cal_period_type_new_full’ [-Wredundant-decls]
   i_cal_period_type_new_full (struct icalperiodtype native);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:174:3: note: previous declaration of ‘i_cal_period_type_new_full’ was here
   i_cal_period_type_new_full (struct icalperiodtype native);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:188:14: warning: redundant redeclaration of ‘i_cal_parser_new_full’ [-Wredundant-decls]
 ICalParser * i_cal_parser_new_full  (icalparser *native,
              ^~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:183:14: note: previous declaration of ‘i_cal_parser_new_full’ was here
 ICalParser * i_cal_parser_new_full  (icalparser *native,
              ^~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:199:3: warning: redundant redeclaration of ‘i_cal_trigger_type_new_full’ [-Wredundant-decls]
   i_cal_trigger_type_new_full (struct icaltriggertype native);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:194:3: note: previous declaration of ‘i_cal_trigger_type_new_full’ was here
   i_cal_trigger_type_new_full (struct icaltriggertype native);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:211:16: warning: redundant redeclaration of ‘i_cal_timezone_new_full’ [-Wredundant-decls]
 ICalTimezone * i_cal_timezone_new_full  (icaltimezone *native,
                ^~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:203:16: note: previous declaration of ‘i_cal_timezone_new_full’ was here
 ICalTimezone * i_cal_timezone_new_full  (icaltimezone *native,
                ^~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:215:7: warning: redundant redeclaration of ‘i_cal_timezone_destroy’ [-Wredundant-decls]
 void  i_cal_timezone_destroy  (icaltimezone *zone);
       ^~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:207:7: note: previous declaration of ‘i_cal_timezone_destroy’ was here
 void  i_cal_timezone_destroy  (icaltimezone *zone);
       ^~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:226:3: warning: redundant redeclaration of ‘i_cal_recur_iterator_new_full’ [-Wredundant-decls]
   i_cal_recur_iterator_new_full (icalrecur_iterator *native,
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:220:3: note: previous declaration of ‘i_cal_recur_iterator_new_full’ was here
   i_cal_recur_iterator_new_full (icalrecur_iterator *native,
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:236:13: warning: redundant redeclaration of ‘i_cal_array_new_full’ [-Wredundant-decls]
 ICalArray * i_cal_array_new_full  (icalarray *native,
             ^~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:231:13: note: previous declaration of ‘i_cal_array_new_full’ was here
 ICalArray * i_cal_array_new_full  (icalarray *native,
             ^~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:245:15: warning: redundant redeclaration of ‘i_cal_geo_type_new_full’ [-Wredundant-decls]
 ICalGeoType * i_cal_geo_type_new_full  (struct icalgeotype native);
               ^~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:241:15: note: previous declaration of ‘i_cal_geo_type_new_full’ was here
 ICalGeoType * i_cal_geo_type_new_full  (struct icalgeotype native);
               ^~~~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:254:14: warning: redundant redeclaration of ‘i_cal_attach_new_full’ [-Wredundant-decls]
 ICalAttach * i_cal_attach_new_full  (icalattach *native,
              ^~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:249:14: note: previous declaration of ‘i_cal_attach_new_full’ was here
 ICalAttach * i_cal_attach_new_full  (icalattach *native,
              ^~~~~~~~~~~~~~~~~~~~~
/git/libical/src/libical-glib/libical-glib-private.h:257:2: error: #endif without #if
 #endif
  ^~~~~
make[2]: *** [src/libical-glib/CMakeFiles/ical-glib.dir/build.make:301: src/libical-glib/CMakeFiles/ical-glib.dir/i-cal-array.c.o] Error 1
make[2]: Leaving directory '/git/libical'
```

and `libical-glib-private.h` is
```
     1	#ifndef LIBICAL_GLIB_PRIVATE_H
     2	#define LIBICAL_GLIB_PRIVATE_H
     3	
     4	#include "libical-glib.h"
     5	
     6	/* Private methods for ICalCompIter */
     7	
     8	ICalCompIter *	i_cal_comp_iter_new_full	(struct icalcompiter native);
     9	
    10	struct icalcompiter 
    11			i_cal_comp_iter_new_default	(void);
    12	
    13	/* Private methods for ICalComponent */
    14	
    15	ICalComponent *	i_cal_component_new_full	(icalcomponent *native,
    16							 GObject *owner);
    17	
    18	/* Private methods for ICalComponent */
    19	
    20	ICalComponent *	i_cal_component_new_full	(icalcomponent *native,
    21							 GObject *owner);
    22	
    23	/* Private methods for ICalDatetimeperiodType */
    24	
    25	ICalDatetimeperiodType *
    26			i_cal_datetimeperiod_type_new_full
    27							(struct icaldatetimeperiodtype native);
    28	
    29	struct icaldatetimeperiodtype 
    30			i_cal_datetimeperiod_type_new_default
    31							(void);
    32	
    33	/* Private methods for ICalDatetimeperiodType */
    34	
    35	ICalDatetimeperiodType *
    36			i_cal_datetimeperiod_type_new_full
    37							(struct icaldatetimeperiodtype native);
    38	
    39	struct icaldatetimeperiodtype 
    40			i_cal_datetimeperiod_type_new_default
    41							(void);
    42	
    43	/* Private methods for ICalTimezonePhase */
    44	
    45	ICalTimezonePhase *
    46			i_cal_timezone_phase_new_full	(struct icaltimezonephase native);
    47	
    48	struct icaltimezonephase 
    49			i_cal_timezone_phase_new_default
    50							(void);
    51	
    52	/* Private methods for ICalTimezonePhase */
    53	
    54	ICalTimezonePhase *
    55			i_cal_timezone_phase_new_full	(struct icaltimezonephase native);
    56	
    57	struct icaltimezonephase 
    58			i_cal_timezone_phase_new_default
    59							(void);
    60	
    61	/* Private methods for ICalRecurrenceType */
    62	
    63	ICalRecurrenceType *
    64			i_cal_recurrence_type_new_full	(struct icalrecurrencetype native);
    65	
    66	struct icalrecurrencetype 
    67			i_cal_recurrence_type_new	(void);
    68	
    69	/* Private methods for ICalRecurrenceType */
    70	
    71	ICalRecurrenceType *
    72			i_cal_recurrence_type_new_full	(struct icalrecurrencetype native);
    73	
    74	struct icalrecurrencetype 
    75			i_cal_recurrence_type_new	(void);
    76	
    77	/* Private methods for ICalTimeSpan */
    78	
    79	ICalTimeSpan *	i_cal_time_span_new_full	(struct icaltime_span native);
    80	
    81	/* Private methods for ICalTimeSpan */
    82	
    83	ICalTimeSpan *	i_cal_time_span_new_full	(struct icaltime_span native);
    84	
    85	/* Private methods for ICalParameter */
    86	
    87	ICalParameter *	i_cal_parameter_new_full	(icalparameter *native,
    88							 GObject *owner);
    89	
    90	/* Private methods for ICalParameter */
    91	
    92	ICalParameter *	i_cal_parameter_new_full	(icalparameter *native,
    93							 GObject *owner);
    94	
    95	/* Private methods for ICalDurationType */
    96	
    97	ICalDurationType *
    98			i_cal_duration_type_new_full	(struct icaldurationtype native);
    99	
   100	/* Private methods for ICalDurationType */
   101	
   102	ICalDurationType *
   103			i_cal_duration_type_new_full	(struct icaldurationtype native);
   104	
   105	/* Private methods for ICalProperty */
   106	
   107	ICalProperty *	i_cal_property_new_full		(icalproperty *native,
   108							 GObject *owner);
   109	
   110	/* Private methods for ICalProperty */
   111	
   112	ICalProperty *	i_cal_property_new_full		(icalproperty *native,
   113							 GObject *owner);
   114	
   115	/* Private methods for ICalReqstatType */
   116	
   117	ICalReqstatType *
   118			i_cal_reqstat_type_new_full	(struct icalreqstattype native);
   119	
   120	struct icalreqstattype 
   121			i_cal_reqstat_type_new_default	(void);
   122	
   123	/* Private methods for ICalReqstatType */
   124	
   125	ICalReqstatType *
   126			i_cal_reqstat_type_new_full	(struct icalreqstattype native);
   127	
   128	struct icalreqstattype 
   129			i_cal_reqstat_type_new_default	(void);
   130	
   131	/* Private methods for ICalTimetype */
   132	
   133	ICalTimetype *	i_cal_timetype_new_full		(struct icaltimetype native);
   134	
   135	struct icaltimetype 
   136			i_cal_timetype_new_default	(void);
   137	
   138	/* Private methods for ICalTimetype */
   139	
   140	ICalTimetype *	i_cal_timetype_new_full		(struct icaltimetype native);
   141	
   142	struct icaltimetype 
   143			i_cal_timetype_new_default	(void);
   144	
   145	/* Private methods for ICalValue */
   146	
   147	ICalValue *	i_cal_value_new_full		(icalvalue *native,
   148							 GObject *owner);
   149	
   150	/* Private methods for ICalValue */
   151	
   152	ICalValue *	i_cal_value_new_full		(icalvalue *native,
   153							 GObject *owner);
   154	
   155	/* Private methods for ICalTimezonetype */
   156	
   157	ICalTimezonetype *
   158			i_cal_timezonetype_new_full	(struct icaltimezonetype native);
   159	
   160	struct icaltimezonetype 
   161			i_cal_timezonetype_new_default	(void);
   162	
   163	/* Private methods for ICalTimezonetype */
   164	
   165	ICalTimezonetype *
   166			i_cal_timezonetype_new_full	(struct icaltimezonetype native);
   167	
   168	struct icaltimezonetype 
   169			i_cal_timezonetype_new_default	(void);
   170	
   171	/* Private methods for ICalPeriodType */
   172	
   173	ICalPeriodType *
   174			i_cal_period_type_new_full	(struct icalperiodtype native);
   175	
   176	/* Private methods for ICalPeriodType */
   177	
   178	ICalPeriodType *
   179			i_cal_period_type_new_full	(struct icalperiodtype native);
   180	
   181	/* Private methods for ICalParser */
   182	
   183	ICalParser *	i_cal_parser_new_full		(icalparser *native,
   184							 GObject *owner);
   185	
   186	/* Private methods for ICalParser */
   187	
   188	ICalParser *	i_cal_parser_new_full		(icalparser *native,
   189							 GObject *owner);
   190	
   191	/* Private methods for ICalTriggerType */
   192	
   193	ICalTriggerType *
   194			i_cal_trigger_type_new_full	(struct icaltriggertype native);
   195	
   196	/* Private methods for ICalTriggerType */
   197	
   198	ICalTriggerType *
   199			i_cal_trigger_type_new_full	(struct icaltriggertype native);
   200	
   201	/* Private methods for ICalTimezone */
   202	
   203	ICalTimezone *	i_cal_timezone_new_full		(icaltimezone *native,
   204							 GObject *owner,
   205							 gboolean is_global_memory);
   206	
   207	void		i_cal_timezone_destroy		(icaltimezone *zone);
   208	
   209	/* Private methods for ICalTimezone */
   210	
   211	ICalTimezone *	i_cal_timezone_new_full		(icaltimezone *native,
   212							 GObject *owner,
   213							 gboolean is_global_memory);
   214	
   215	void		i_cal_timezone_destroy		(icaltimezone *zone);
   216	
   217	/* Private methods for ICalRecurIterator */
   218	
   219	ICalRecurIterator *
   220			i_cal_recur_iterator_new_full	(icalrecur_iterator *native,
   221							 GObject *owner);
   222	
   223	/* Private methods for ICalRecurIterator */
   224	
   225	ICalRecurIterator *
   226			i_cal_recur_iterator_new_full	(icalrecur_iterator *native,
   227							 GObject *owner);
   228	
   229	/* Private methods for ICalArray */
   230	
   231	ICalArray *	i_cal_array_new_full		(icalarray *native,
   232							 GObject *owner);
   233	
   234	/* Private methods for ICalArray */
   235	
   236	ICalArray *	i_cal_array_new_full		(icalarray *native,
   237							 GObject *owner);
   238	
   239	/* Private methods for ICalGeoType */
   240	
   241	ICalGeoType *	i_cal_geo_type_new_full		(struct icalgeotype native);
   242	
   243	/* Private methods for ICalGeoType */
   244	
   245	ICalGeoType *	i_cal_geo_type_new_full		(struct icalgeotype native);
   246	
   247	/* Private methods for ICalAttach */
   248	
   249	ICalAttach *	i_cal_attach_new_full		(icalattach *native,
   250							 GObject *owner);
   251	
   252	/* Private methods for ICalAttach */
   253	
   254	ICalAttach *	i_cal_attach_new_full		(icalattach *native,
   255							 GObject *owner);
   256	#endif
   257	#endif
```

**Comment by winterz** [comment] 2017-10-14 19:55
build the 2.0 branch with cmake 3.9.3 works fine for me.
not sure what  v2.0.0-360-ga2bc4844 is.

which options are you passing to CMake?

**Comment by dilyanpalauzov** [comment] 2017-10-14 21:21
v2.0.0-360-ga2bc4844 is the output of `git describe`: 360 commits away from tag v2.0.0 at a2bc4844.

I cannot reproduce the problem, but looking at `libical-glib-private.h` I posted, everything is included twice, except
```
1	#ifndef LIBICAL_GLIB_PRIVATE_H
2	#define LIBICAL_GLIB_PRIVATE_H
3	
4	#include "libical-glib.h"
```

so most probably, two instances of libical-glib/tools/generator were started in parallel, which created everything double, except the opening macros.

**Comment by winterz** [comment] 2017-10-16 14:04
are you doing in-source builds ?

**Comment by winterz** [comment] 2017-10-22 15:57
I can't reproduce this in the master branch.
I tried on linux, both in-source and out-of-source builds.  I tried make -j10.

**Comment by dilyanpalauzov** [comment] 2017-10-31 18:24
`libical-glib-private.h` is generated in `src/libical-glib/CMakeList.txt`:

```
add_custom_command (
  OUTPUT ${LIBICAL_GLIB_SOURCES} ${CMAKE_CURRENT_BINARY_DIR}/libical-glib-private.h ${CMAKE_CURRENT_BINARY_DIR}/i-cal-forward-declarations.h
  COMMAND ${EXECUTABLE_OUTPUT_PATH}/src-generator "${CMAKE_CURRENT_SOURCE_DIR}/tools" "${CMAKE_CURRENT_SOURCE_DIR}/api"
  DEPENDS ${EXECUTABLE_OUTPUT_PATH}/src-generator ${xml_files}
)
```
and used in
```
list(APPEND LIBICAL_GLIB_SOURCES
  ${CMAKE_CURRENT_BINARY_DIR}/libical-glib-private.h
  ${CMAKE_CURRENT_BINARY_DIR}/i-cal-object.c
  ${CMAKE_CURRENT_BINARY_DIR}/i-cal-object.h
)
```
LIBICAL_GLIB_SOURCES is used in 
```
add_library(ical-glib ${LIBRARY_TYPE} ${LIBICAL_GLIB_SOURCES})
add_library(ical-glib-static STATIC ${LIBICAL_GLIB_SOURCES})
```

so `libical-glib-private.h` is used as source for two libraries.

I myself cannot reproduce the problem, it happened once and I think the problem was that the generator was run twice in parallel.

https://cmake.org/pipermail/cmake/2008-October/024491.html says this can be solved if the targets ical-glib and ical-glib-static are serialized, so they don't interfere with each other in a parallel build.

https://cmake.org/Bug/view.php?id=10082 suggests adding `add_dependencies(ical-glib ical-glib-static)`

**Comment by winterz** [comment] 2017-11-16 23:24
wish we could reliably reproduce.
I'm tempted to thrown in add_dependencies() as you suggest.

**Comment by krop** [comment] 2017-11-27 14:49
I can't reproduce locally (tested with CMake 3.9.5). Which parameters do you use when running CMake ?

**Comment by dilyanpalauzov** [comment] 2017-11-27 16:05
As I wrote already twice, this happened once and I cannot reproduce it anymore.

**Comment by krop** [comment] 2017-11-27 16:09
Ok, thank you for the feedback. Closing as we cannot find a way to reproduce the issue.
We can revisit it later if needed.

**Closed by krop** 2017-11-27 16:09 UTC
